/**
 * User Slice for Redux State Management
 *
 * This file defines a Redux slice for managing user authentication state.
 * A Redux slice is a portion of the Redux store that handles a specific domain of state.
 * It includes the initial state, reducers, and actions for that domain.
 *
 * Key concepts:
 * - Slice: A collection of reducer logic and actions for a specific feature.
 * - Reducer: A function that updates the state based on actions.
 * - Actions: Objects that describe changes to the state.
 * - Selectors: Functions to retrieve specific pieces of state.
 */

import { createSlice } from "@reduxjs/toolkit";

// TypeScript interface defining the shape of the user state in the Redux store.
// This defines the structure of the user state stored in Redux.
// It includes authentication token and user details.
export type UserState = {
    token: string | null;
    user: {
        user_id: number;
        first_name: string;
        last_name: string;
        email: string;
        role: string;
    } | null;
};

const initialState: UserState = {
    token: null,
    user: null,
} // Initial state: no user is logged in by default.

// Create a Redux slice using RTK's createSlice.
// This generates action creators and reducers automatically.
const userSlice = createSlice({
    name: 'user', // Unique name for this slice, used as a key in the store
    initialState, // The initial state for this slice
    reducers: { // Reducer functions that handle state updates
        // Action to handle successful login
        loginSuccess: (state, action) => {
            state.token = action.payload.token; // Store the JWT token from login response
            state.user = action.payload.user; // Store user details from login response
        },
        // Action to handle logout
        logout: (state) => {
            state.token = null; // Clear the token
            state.user = null; // Clear user data
        }
    }
})

// Export the action creators generated by createSlice.
// These can be dispatched from components to update the state.
export const { loginSuccess, logout } = userSlice.actions;

// Export the reducer to be included in the store.
export default userSlice.reducer;